server:
  port: 8888

spring:
  application:
    name: querydsl
  jpa:
    properties:
      hibernate:
        dialect: com.example.querydsl.config.MySQLChineseDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true

zookeeper:
  enableZK: false
  companyId: "dev-jdy"
  defaultHost: 192.168.2.23:2181
  rootLoginUrl: /role